name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build with JDK ${{ matrix.jdk }}
    strategy:
      matrix:
        jdk: [1.8, 11, 14]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven Repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-repository-${{ runner.os }}
          restore-keys: |
            maven-repository-

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Build and run Tests
        run: mvn -B clean verify

  release:
    name: Release
    env:
      BINTRAY_PACKAGE: org.tunnat:maven-parent
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Set Release Version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})

      - uses: actions/checkout@v2

      - name: Cache Maven Repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-repository-${{ runner.os }}
          restore-keys: |
            maven-repository-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Deploy to Bintray
        uses: simontunnat/action-maven-deploy@v1
        with:
          username: ${{ secrets.BINTRAY_USERNAME }}
          password: ${{ secrets.BINTRAY_PASSWORD }}
          repository: https://api.bintray.com/maven/${{ secrets.BINTRAY_USERNAME }}/maven/${{ env.BINTRAY_PACKAGE }}/;publish=0
          maven-args: -P release -Drevision=${{ env.RELEASE_VERSION }}

      - name: Sync to Maven Central
        uses: simontunnat/action-bintray-maven-central-sync@v1
        with:
          username: ${{ secrets.BINTRAY_USERNAME }}
          password: ${{ secrets.BINTRAY_PASSWORD }}
          package: ${{ env.BINTRAY_PACKAGE }}
          version: ${{ env.RELEASE_VERSION }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Version ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
